/* GENERATED by tools/build_i18n.js from i18n/strings.json - edit the JSON, then rebuild. */
window.CG_I18N = {
 "_note": "Every word the game shows, by language. The language is picked with ?lan=hi (or ?lang=hi); anything else is English. After editing, run tools/build_i18n.js - it writes i18n/strings.js, which the game loads as a <script> because file:// refuses fetch(). Over http the game fetches this JSON directly. {n}-style braces are filled in by the game; an entry with one/other picks by the count.",
 "en": {
  "meta": {
   "name": "English"
  },
  "title": {
   "page": "Cliff Cross",
   "word1": "CLIFF",
   "word2": "CROSS",
   "play": "PLAY"
  },
  "boot": {
   "loading": "loading art…",
   "error": "ERROR: {msg}",
   "errorLine": " (line {n})",
   "missing": "{n} asset(s) missing"
  },
  "lesson": {
   "title": "Distance formula lesson"
  },
  "select": {
   "title1": "CHOOSE A",
   "title2": "CLIMB",
   "stars": "{n} of {total} stars collected",
   "locked": "LOCKED",
   "clearFirst": "clear stage {n} first",
   "endless": "ENDLESS",
   "home": "HOME"
  },
  "stages": {
   "1": {
    "name": "MEADOW START",
    "sub": "distance along a line"
   },
   "2": {
    "name": "BLOSSOM TRAIL",
    "sub": "down the slope: 3-4-5"
   },
   "3": {
    "name": "ORCHARD CLIMB",
    "sub": "twice the size: 6-8-10"
   },
   "4": {
    "name": "SUNSET RIDGE",
    "sub": "the long climb: 5-12-13"
   },
   "5": {
    "name": "WIND GAP",
    "sub": "scaled up: 9-12-15"
   },
   "6": {
    "name": "THUNDER STEPS",
    "sub": "steeper climb: 8-15-17"
   },
   "7": {
    "name": "HIGH MEADOW",
    "sub": "the big drop: 12-16-20"
   },
   "8": {
    "name": "GOLDEN SUMMIT",
    "sub": "all six triples"
   }
  },
  "intro": {
   "line1": "Oops, the road is broken!",
   "line2": "To cross this gap, we need to know the distance between its two ends.",
   "line3": "Let’s explore how to find that on a coordinate plane!",
   "noLessonTitle": "THE LESSON DIDN’T OPEN",
   "noLessonStrap": "Check that the learn folder sits beside the game - or carry on to the question.",
   "continue": "CONTINUE",
   "continueSub": "On to the question"
  },
  "gap": {
   "questionFirst": "Let’s pick the right length for the plank!",
   "questionAgain": "Let’s try another length for the plank.",
   "tipOpen": "Tap the red button to open the ruler",
   "tipPick": "Tap the number of units the plank needs",
   "tipDrop": "Tap GO to cut the plank",
   "go": "GO",
   "units": {
    "one": "{n} unit",
    "other": "{n} units"
   }
  },
  "fx": {
   "tryAgain": "TRY AGAIN!",
   "perfect": "PERFECT FIT!",
   "go": "GO!",
   "firstTry": "FIRST TRY!",
   "across": "ACROSS!"
  },
  "win": {
   "title": "YOU DID IT!",
   "mission": "Every gap crossed — mission complete!",
   "planks": "planks",
   "firstTry": "first try",
   "newBest": "NEW BEST TIME!",
   "next": "NEXT",
   "nextSub": "On to the next climb",
   "map": "MAP",
   "retry": "RETRY",
   "retrySub": "Keep all three hearts",
   "stageMap": "STAGE MAP",
   "playAgain": "PLAY AGAIN",
   "playAgainSub": "Another run at it",
   "lesson": "BACK TO THE LESSON",
   "lessonSub": "On to the next part"
  },
  "over": {
   "title": "OUT OF HEARTS!",
   "strap": "Three planks missed the mark. Take another look, or go again!",
   "fitted": {
    "one": "{n} plank fitted this run",
    "other": "{n} planks fitted this run"
   },
   "lesson": "BACK TO THE LESSON",
   "lessonSub": "Revisit the distance formula",
   "playAgain": "PLAY AGAIN",
   "playAgainSub": "Three fresh hearts"
  },
  "road": {
   "check": "CHECK {n}",
   "metres": "{n}m",
   "finish": "FINISH"
  },
  "axis": {
   "x": "x",
   "y": "y"
  }
 },
 "hi": {
  "meta": {
   "name": "हिन्दी"
  },
  "title": {
   "page": "क्लिफ़ क्रॉस",
   "word1": "क्लिफ़",
   "word2": "क्रॉस",
   "play": "खेलें"
  },
  "boot": {
   "loading": "चित्र लोड हो रहे हैं…",
   "error": "त्रुटि: {msg}",
   "errorLine": " (पंक्ति {n})",
   "missing": "{n} फ़ाइलें नहीं मिलीं"
  },
  "lesson": {
   "title": "दूरी सूत्र का पाठ"
  },
  "select": {
   "title1": "एक चढ़ाई",
   "title2": "चुनें",
   "stars": "{total} में से {n} तारे मिले",
   "locked": "बंद है",
   "clearFirst": "पहले स्तर {n} पूरा करें",
   "endless": "अनंत",
   "home": "होम"
  },
  "stages": {
   "1": {
    "name": "घास का मैदान",
    "sub": "एक सीधी रेखा पर दूरी"
   },
   "2": {
    "name": "फूलों की पगडंडी",
    "sub": "ढलान से नीचे: 3-4-5"
   },
   "3": {
    "name": "बाग़ की चढ़ाई",
    "sub": "दोगुना आकार: 6-8-10"
   },
   "4": {
    "name": "सूर्यास्त की चोटी",
    "sub": "लंबी चढ़ाई: 5-12-13"
   },
   "5": {
    "name": "हवा का दर्रा",
    "sub": "बड़ा पैमाना: 9-12-15"
   },
   "6": {
    "name": "गरज की सीढ़ियाँ",
    "sub": "और खड़ी चढ़ाई: 8-15-17"
   },
   "7": {
    "name": "ऊँचा मैदान",
    "sub": "बड़ी ढलान: 12-16-20"
   },
   "8": {
    "name": "सुनहरी चोटी",
    "sub": "सभी छह त्रिक"
   }
  },
  "intro": {
   "line1": "अरे! सड़क टूटी हुई है!",
   "line2": "इस खाई को पार करने के लिए हमें इसके दोनों सिरों के बीच की दूरी जाननी होगी।",
   "line3": "चलो निर्देशांक तल पर इसे पता करना सीखें!",
   "noLessonTitle": "पाठ खुल नहीं पाया",
   "noLessonStrap": "देखें कि learn फ़ोल्डर गेम के साथ रखा है - या सीधे सवाल पर चलें।",
   "continue": "आगे बढ़ें",
   "continueSub": "सवाल की ओर"
  },
  "gap": {
   "questionFirst": "चलो तख़्ते के लिए सही लंबाई चुनें!",
   "questionAgain": "चलो तख़्ते के लिए कोई और लंबाई आज़माएँ।",
   "tipOpen": "रूलर खोलने के लिए लाल बटन दबाएँ",
   "tipPick": "तख़्ते को जितनी इकाइयाँ चाहिए, वह संख्या दबाएँ",
   "tipDrop": "तख़्ता काटने के लिए ‘जाओ’ दबाएँ",
   "go": "जाओ",
   "units": {
    "one": "{n} इकाई",
    "other": "{n} इकाइयाँ"
   }
  },
  "fx": {
   "tryAgain": "फिर कोशिश करो!",
   "perfect": "एकदम सही!",
   "go": "चलो!",
   "firstTry": "पहली बार में!",
   "across": "पार हो गए!"
  },
  "win": {
   "title": "तुमने कर दिखाया!",
   "mission": "हर खाई पार — मिशन पूरा!",
   "planks": "तख़्ते",
   "firstTry": "पहली बार में",
   "newBest": "नया सबसे अच्छा समय!",
   "next": "आगे",
   "nextSub": "अगली चढ़ाई की ओर",
   "map": "नक़्शा",
   "retry": "फिर से",
   "retrySub": "तीनों दिल बचाकर",
   "stageMap": "स्तर नक़्शा",
   "playAgain": "फिर खेलें",
   "playAgainSub": "एक और कोशिश",
   "lesson": "पाठ पर वापस",
   "lessonSub": "अगले भाग की ओर"
  },
  "over": {
   "title": "दिल ख़त्म!",
   "strap": "तीन तख़्ते सही नहीं बैठे। एक बार फिर देखो, या दोबारा कोशिश करो!",
   "fitted": {
    "one": "इस बार {n} तख़्ता लगा",
    "other": "इस बार {n} तख़्ते लगे"
   },
   "lesson": "पाठ पर वापस",
   "lessonSub": "दूरी सूत्र फिर से देखें",
   "playAgain": "फिर खेलें",
   "playAgainSub": "तीन नए दिल"
  },
  "road": {
   "check": "चेक {n}",
   "metres": "{n} मी",
   "finish": "समाप्त"
  },
  "axis": {
   "x": "x",
   "y": "y"
  }
 }
};
