#!/usr/bin/env node
/* i18n/strings.json -> i18n/strings.js
 *
 * The game ships over file://, where fetch() is refused, so the string table
 * is loaded as a plain <script> (like assets/audio/sfx.js). This wraps the
 * JSON - the file to edit - as that script, and checks every language has
 * every key English has (and no extras), so a gap is caught here and not as
 * a raw key on a child's screen.
 *
 *   node tools/build_i18n.js
 */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const src = path.join(root, 'i18n', 'strings.json'), dst = path.join(root, 'i18n', 'strings.js');

const table = JSON.parse(fs.readFileSync(src, 'utf8'));
const langs = Object.keys(table).filter(k => k[0] !== '_');
if (!table.en) throw new Error('strings.json has no "en" - English is the fallback and must exist');

function keys(o, prefix, out) {
  for (const k of Object.keys(o)) {
    const v = o[k], p = prefix ? prefix + '.' + k : k;
    if (v && typeof v === 'object' && !('one' in v && 'other' in v)) keys(v, p, out);
    else out.push(p);
  }
  return out;
}
const en = keys(table.en, '', []);
let bad = 0;
for (const lang of langs) {
  if (lang === 'en') continue;
  const have = new Set(keys(table[lang], '', []));
  const missing = en.filter(k => !have.has(k)), extra = [...have].filter(k => !en.includes(k));
  for (const k of missing) { console.error(`${lang}: missing ${k} (falls back to English)`); bad++; }
  for (const k of extra) { console.error(`${lang}: ${k} is not an English key - a typo?`); bad++; }
}

const out = '/* GENERATED by tools/build_i18n.js from i18n/strings.json - edit the JSON, then rebuild. */\n' +
            'window.CG_I18N = ' + JSON.stringify(table, null, 1) + ';\n';
fs.writeFileSync(dst, out);
console.log(`wrote ${path.relative(root, dst)}: ${langs.join(', ')} (${en.length} keys)${bad ? `, ${bad} problem(s)` : ''}`);
process.exit(bad ? 1 : 0);
